import React from "react";
import reviews from "@/data/SingleServices/Testimonials/Testimonials";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const Testimonials = () => {
  return (
    <>
      <section className="testimonial-area">
        <div className="custom-container">
          <div className="testimonial-slider-wrap">
            <div className="testimonial-slider swiper">
              <Swiper
                loop={true}
                spaceBetween={30}
                navigation={{
                  nextEl: ".swiper-button-next",
                  prevEl: ".swiper-button-prev",
                }}
                speed={800}
                easing="easeOutQuad"
                modules={[Navigation]}
              >
                {reviews.map((item) => (
                  <SwiperSlide className="testimonial-item" key={item.id}>
                    <div className="testimonial-item-body">
                      <img decoding="async" className="animation-slide-right bg-shape" src="/images/bg-shape-3-1.svg" alt="Background Shape" />
                      <span className="platform-name">{item.source}</span>
                      {/* <h2>Platform helped me to increase my sales and revenue generated by bluebase technologies</h2> */}
                      <p>{item.review}</p>
                      <div className="author-box d-flex align-items-center">
                        <img decoding="async" src="/images/placeholder-image.png" alt="Serana Belluci" />
                        <div className="author-box-content">
                          <h5>David Wright</h5>
                          {/* <p>Product Designer</p> */}
                        </div>
                      </div>
                    </div>
                  </SwiperSlide>
                ))}
              </Swiper>
            </div>
            <div className="swiper-button-next">
              <i className="las la-arrow-right"></i>
            </div>
            <div className="swiper-button-prev">
              <i className="las la-arrow-left"></i>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Testimonials;
